version: '3'
services:
  dbpostgres:
    image: postgres
    volumes:
      - ./amigoscode-data:/var/lib/postgresql/data
    ports:
      - "5444:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: amigoscode

volumes:
  amigoscode-data: